# A CSV file with sample and full path for the corresponding CRAM file
crams: ""

# A PED file 
ped: ""

# A file with HPO IDs for the proband, one on each line
hpo: ""

# full path for exomiser jar and application.properties
exomiser_jar: ""
exomiser_app: ""

# full path of the fasta reference you would like to align to
reference: ""

# sex chromosomes in the fasta reference included as {reference}
xchrom: ""
ychrom: ""

# the BED file of target regions for the exome
target_bed: ""

# the BED file of low-complexity regions for the genome
LCR_bed: ""

# full path for binaries of some tools that have not been containerized yet
DISCVRSeq: ""
triodenovo: ""
